version: '2.2'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./revoked.crl:/etc/ssl/revoked.crl
      - ./install-ssl-snakeoil.sh:/docker-entrypoint.d/99-snakeoil.sh

